version: '1'

services:
  app:
    image: topeducationapp:latest
    build:
      context: .
    container_name: topeducationapp
    depends_on:
      - topeducationdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://topeducationdb:5432/topeducation
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgre
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8001:3000"

  topeducationdb:
    image: postgres:latest
    container_name: topeducation-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: topeducation
    command: ["postgres", "-c", "max_connections=200", "-c", "shared_buffers=256MB", "-c", "effective_cache_size=768MB"]
    volumes:
      - topeducation-data:/var/lib/postgresql/data

volumes:
  topeducation-data:


